"""add usage analytics fields

Revision ID: 1b3d96b80d10
Revises: ef4fe9610e92
Create Date: 2026-03-09 12:43:58.470556

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1b3d96b80d10"
down_revision: Union[str, Sequence[str], None] = "ef4fe9610e92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_logs", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("usage_logs", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.add_column(
        "usage_logs",
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "usage_logs",
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=True),
    )
    op.add_column("usage_logs", sa.Column("total_tokens", sa.Integer(), nullable=True))
    op.add_column(
        "usage_logs",
        sa.Column(
            "include_in_user_analytics",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_usage_logs_include_in_user_analytics"),
        "usage_logs",
        ["include_in_user_analytics"],
        unique=False,
    )
    op.create_index(
        "ix_usage_logs_session_id_created_at",
        "usage_logs",
        ["session_id", "created_at"],
        unique=False,
    )

    op.execute(
        """
        UPDATE usage_logs
        SET
            input_tokens = COALESCE(
                NULLIF(BTRIM(usage_json ->> 'input_tokens'), '')::numeric::integer,
                0
            ),
            output_tokens = COALESCE(
                NULLIF(BTRIM(usage_json ->> 'output_tokens'), '')::numeric::integer,
                0
            ),
            cache_creation_input_tokens = COALESCE(
                NULLIF(
                    BTRIM(usage_json ->> 'cache_creation_input_tokens'),
                    ''
                )::numeric::integer,
                0
            ),
            cache_read_input_tokens = COALESCE(
                NULLIF(BTRIM(usage_json ->> 'cache_read_input_tokens'), '')::numeric::integer,
                0
            )
        WHERE usage_json IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE usage_logs
        SET
            input_tokens = COALESCE(input_tokens, 0),
            output_tokens = COALESCE(output_tokens, 0),
            cache_creation_input_tokens = COALESCE(cache_creation_input_tokens, 0),
            cache_read_input_tokens = COALESCE(cache_read_input_tokens, 0),
            total_tokens =
                COALESCE(input_tokens, 0)
                + COALESCE(output_tokens, 0)
                + COALESCE(cache_creation_input_tokens, 0)
                + COALESCE(cache_read_input_tokens, 0)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_logs_session_id_created_at", table_name="usage_logs")
    op.drop_index(
        op.f("ix_usage_logs_include_in_user_analytics"), table_name="usage_logs"
    )
    op.drop_column("usage_logs", "include_in_user_analytics")
    op.drop_column("usage_logs", "total_tokens")
    op.drop_column("usage_logs", "cache_read_input_tokens")
    op.drop_column("usage_logs", "cache_creation_input_tokens")
    op.drop_column("usage_logs", "output_tokens")
    op.drop_column("usage_logs", "input_tokens")
    # ### end Alembic commands ###
