"""empty message

Revision ID: ef4fe9610e92
Revises: a5582f015bfd
Create Date: 2026-03-02 15:02:20.877823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef4fe9610e92"
down_revision: Union[str, Sequence[str], None] = "a5582f015bfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_create_jobs",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_create_jobs_status"),
        "memory_create_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_create_jobs_user_id"),
        "memory_create_jobs",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_tool_executions_session_id_created_at_id"),
        table_name="tool_executions",
    )
    op.create_index(
        "ix_tool_executions_session_id_updated_at_id",
        "tool_executions",
        ["session_id", "updated_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tool_executions_session_id_updated_at_id", table_name="tool_executions"
    )
    op.create_index(
        op.f("ix_tool_executions_session_id_created_at_id"),
        "tool_executions",
        ["session_id", "created_at", "id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_memory_create_jobs_user_id"), table_name="memory_create_jobs"
    )
    op.drop_index(op.f("ix_memory_create_jobs_status"), table_name="memory_create_jobs")
    op.drop_table("memory_create_jobs")
    # ### end Alembic commands ###
